### PR TITLE
Suppress shell session exit messages on macOS

### LINKED ISSUE #91: Completion is sometimes ending my Bash Session on Mac OS
Output then looks like this ("mvn cl[TAB]"):
```
> mvn clgrep: /{PARENT_PATH}/pom.xml
Saving session...
...saving history...truncating history files...
...completed.: No such file or directory
ean 
```
FYI: The `/{PARENT_PATH}/pom.xml` does exist and is parent with pom packaging.

### PR DESCRIPTION
**Pull request by dscorbett**
Fixes #91.

### CODE REVIEW

**Comment by mosabua** [comment]
That seems fine to me .. although is it really only the Apple terminal that is affected  .. what it other console like iterm is used?

**Comment by dscorbett** [comment]
On macOS, /etc/bashrc ends with `[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"`. In iTerm and iTerm2, `TERM_PROGRAM` is `iTerm.app`. Only /etc/bashrc_Apple_Terminal exists by default, which is the file responsible for these session termination messages. I checked for specifically `[ "$TERM_PROGRAM" = "Apple_Terminal" ]` because that is the only terminal where I could reproduce the problem. On the other hand, I suppose it is safe enough to (re)define `shell_session_save` unconditionally. I’ll push that change shortly.

**Comment by mosabua** [comment]
Does that have any negative effects on Linux ?

**Comment by dscorbett** [comment]
I tried it on Linux without any difference in behavior. `shell_session_save` is a macOS thing; I don’t think it is used on Linux. Even if it is, its effect is highly limited in scope, since `_realpath` is only ever called in a subshell.

**Comment by mosabua** [comment]
Excellent .. I am good with this then. @juven  ?

**Pull request merged**
