### PR TITLE
protected grep from alias, join some sed commands and don't load profile if not needed

### PR DESCRIPTION
**Pull request by glhez**
Hello,

I've pushed 3 commits:
- A protection against grep alias; if you do `alias grep='grep --color -Hn'`, then the `$common_plugins` local will contains line starting with `(standard input):<line number>:`.
- An optimisation on sed, to not invoke it several times. This is better for Windows. 
- An optimisation on profile, which don't have to be loaded unless  `-P` or `--active-profiles` is used.

**Note:** I used a trick of sed, which can remove the `\n` delimiter. eg: `sed -e s/\n/\|/g` does the same as `tr '\n' '|'`. This works on Git for Windows, did not test on a Linux bash.

### CODE REVIEW

**Comment by mosabua** [comment]
@glhez did you test this on Linux and Mac?

**Comment by glhez** [comment]
Yep. Tested on:

- Linux 4.0.5-gentoo / bash: version 4.3.39(1)-release (x86_64-pc-linux-gnu)
- Windows 7 Pro / bash: 4.3.39(3)-release (x86_64-pc-msys + git version 2.5.0.windows.1)

Don't have a Mac. 

I've added two more commit: 

- You can replace new line with sed, but it is a bit more complicated than I though. 
- The second commit patch this case:

```
$ mvn v[TAB]
validate   verify <-- (phase)
$ mvn ver[TAB]
verify <-- phase
$ mvn vers[TAB]
versions: <-- goal
```

Now it display (here under linux):

```
$ mvn ver
verify     versions:  vertx: <-- phase + goal
```

Also, I think the before last if (`elif [[ ${cur} == *:* ]] ; then`) can be completely done by the last task.

**Comment by glhez** [comment]
I mainly replaced old commit due to wrong mail being referenced. It is also rebase against master for all that matter.

**Comment by glhez** [comment]
I'm closing my PR because of the newly drastic change I've made ... and the fact they were never considered since 2015...

You may still read those:
- I've prefixed cd by builtin like #92 
- I've prefixed sed and grep by command.
- I've used mapfile and shellcheck to the whole file; this avoid use of IFS and make the code easier to read (to me, at least)
- I've used two function rather than a N variables and indirection
- I fixed the way that the completion was reading pom / settings for profile even if it was not needed
- I've applied a consistent indentation of two spaces and use a java-ish syntax (the `foobar() { LF }` thing)

**Pull request closed without merging**
