### PR TITLE
Support Maven Wrapper, too

### PR DESCRIPTION
**Pull request by SchulteMarkus**

### CODE REVIEW

**Comment by mosabua** [comment]
lgtm .. wdyt @juven ?

**Comment by juven** [comment]
lgtm @mosabua

**Comment by jiri-pejchal** [comment]
@SchulteMarkus does the completion work when the maven wrapper is invoked from the working directory? I have no completion for `./mvnw in[TAB]`.


`mvnw` without `./` works fine:
```
$ mvnw in[TAB]
initialize         install            integration-test
```

**Comment by mosabua** [comment]
It works for me on Ubuntu with bash 4.4.20 ... what shell are you using?

**Comment by jiri-pejchal** [comment]
Sorry, I had an older maven bash completion active. This works as expected.

**Pull request merged**
